version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      runas: root